baseURL = "https://ohdoylerules.com/"
languageCode = "en-us"
title = "James Doyle"

# theme = "odr"
theme = "odr-hack"

verbose = true
verboseLog = true

copyright = "This work is licensed under The MIT License (MIT)."

pygmentsCodeFences = true
pygmentsStyle = "dracula"

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = "James Doyle"
  email = "james2doyle@gmail.com"

[permalinks]
  post = "/:title/"

[taxonomies]
  category = "category"
  tag = "tags"

[params]
  Description = "The personal blog of James Doyle (james2doyle) Web Developer in Canada."
  Date_format = "January 2, 2006"
  Email = "james2doyle@gmail.com"
  Twitter = "james2doyle"
  Github = "james2doyle"
  Googleplus = "109231487156400680487"
  Referral_code = "https://www.digitalocean.com/?refcode=baa9cb97566c"
  Author_blurb = "I'm a full-stack developer, co-organizer of <a href=\"https://www.meetup.com/vancouver-php\" title=\"PHP Vancouver\" target=\"_blank\">PHP Vancouver</a> meetup, and winner of a <a href=\"http://www.canadianbusiness.com/innovation/developer-30-under-30-gallery/image/20/\" title=\"Canadian Developer 30 under 30 award\" target=\"_blank\">Canadian Developer 30 under 30 award</a>. I'm a huge Open Source advocate and contributor to a lot of projects in my community. When I am not sitting at a computer, I'm trying to perfect some other skill."
  Gravatar = "https://www.gravatar.com/avatar/b7375c88e1864c4ddf0d7bdab58e4cca?s=120&d=mm&r=g"
