baseURL = "https://ohdoylerules.com/"
languageCode = "en-us"
title = "James Doyle"

theme = "odr"

# verbose output
verbose = true
# verbose logging
verboseLog = true

copyright = "This work is licensed under The MIT License (MIT)."

[author]
  name = "James Doyle"
  email = "james2doyle@gmail.com"

[permalinks]
  post = "/:title/"

[taxonomies]
  category = "category"
  tag = "tags"

[params]
  Description = "The personal blog of James Doyle (james2doyle) Web Developer in Vancouver, B.C, Canada."
  Date_format = "January 1st, 2000"
  Email = "james2doyle@gmail.com"
  Twitter = "james2doyle"
  Github = "james2doyle"
  Googleplus = "109231487156400680487"
  Referral_code = "https://www.digitalocean.com/?refcode=baa9cb97566c"
  Author_blurb = "I am a full-stack developer at <a href=\"http://invokemedia.com\" target=\"_blank\" title=\"Invoke\">Invoke</a>, co-creator of <a href=\"https://github.com/PhileCMS/Phile\" title=\"PhileCMS\" target=\"_blank\">PhileCMS</a>. I am a huge Open Source advocate and contributor to a lot of projects in my community. When I am not sitting at a computer, I am trying to perfect some other skill."
  Author_helpline_title = "Need Help?"
  Author_helpline = "Are you having trouble with something? I can give you some advice, instruction, or <em>even look at your code</em>! All of this, for only <a href=\"http://bitcoin.com/\" target=\"_blank\" title=\"What is BitCoin?\"><strong>0.02btc/hour</strong></a>. Or we can work something out."
  Gravatar = "https://www.gravatar.com/avatar/b7375c88e1864c4ddf0d7bdab58e4cca?s=120&d=mm&r=g"
  Unblock_us = "http://unblk.us/vrtM"
