name = "ODR-Hack"
license = "MIT"
licenselink = "https://github.com/james2doyle/ohdoylerules/blob/master/LICENSE.md"
description = ""
homepage = "https://www.ohdoylerules.com/"
tags = []
features = []
min_version = "0.72"

[author]
  name = "James Doyle"
  homepage = "https://www.ohdoylerules.com/"
