# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Odr"
license = "MIT"
licenselink = "https://github.com/james2doyle/ohdoylerules/blob/master/LICENSE.md"
description = ""
homepage = "https://www.ohdoylerules.com/"
tags = []
features = []
min_version = "0.20"

[author]
  name = "James Doyle"
  homepage = "https://www.ohdoylerules.com/"
